apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: default
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/stress:latest
      resources:
        limits:
          memory: "250Mi"
        requests:
          memory: "150Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "175M", "--vm-hang", "1"]
