apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: default
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          cpu: "10"
        requests:
          cpu: "10"
